name: padel
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.12
  cloud_functions: ^3.2.12
  country_code_picker: ^2.0.2
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  firebase_remote_config: ^2.0.6
  firebase_storage: ^10.2.12
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.3
  flutter_datetime_picker: ^1.5.1
  flutter_image_slideshow: ^0.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.3.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  intl: ^0.17.0
  package_info: ^2.0.2
  permission_handler: ^9.2.0
  phone_number: ^0.12.0+2
  pin_code_fields: ^7.4.0
  provider: ^6.0.2
  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
