name: padel
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  country_code_picker: ^2.0.2
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  image_picker: ^0.8.5
  phone_number: ^0.12.0+2
  pin_code_fields: ^7.4.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
